[package]
name = "nbsp"
description = "non-breaking space: a thoughtful community forum platform"
repository = "https://github.com/bearbearean/nbsp"
license = "AGPL-3.0-or-later"
edition = "2024"
version = "0.0.0"

[lints]
rust.missing_docs = "warn"
clippy.missing_docs_in_private_items = "warn"

[dependencies]
axum = "0.8.9"
memory-serve = "2.3.0"
tokio = { version = "1.53.1", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.7.0", features = ["request-id", "trace", "util"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }

[build-dependencies]
memory-serve = "2.3.0"
